name: Build Multi-Platform

on:
  push:
    tags:
      - 'v*'  # v1.0, v2.1 같은 태그 푸시할 때

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest  # ← 여기서 Windows exe 빌드!
            platform: windows
          - os: macos-latest
            platform: macos

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install pyinstaller PyQt5
    
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed main.py
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: app-${{ matrix.platform }}
        path: dist/
